[project]
name = "{{ project_slug }}"
version = "0.1.0"
description = "Proyecto {{ project_name }}"
authors = [
  { name = "Aldo A. Villagra B.", email = "aldovillagra@gmail.com" }
]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">= {{ python_version }}"

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: {{ python_version }}",
]

dependencies = [
    "typer",
    "pydantic-settings",
    "python-dotenv",
    "rich",
    "tomli>=2.0; python_version < '3.11'",  # en Python 3.12 ya no se usa
    "tomli-w>=1.2.0",
    "pandas[excel,output-formatting,parquet,performance]",
    "sqlalchemy",
    "psycopg[binary]",
]

[dependency-groups]
dev = [
    "ruff",
    "pyright",
    "ipdb",
    "ipython",
    "mypy",
    "isort",
    "ipython",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "pytest-mock",
    "faker",
    "hypothesis",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocstrings-python",
]

# Script
[project.scripts]
{{ package_name }} = "{{ package_name }}.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = [
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--cov={{ package_name }}",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
]

[tool.coverage.run]
branch = true
source = ["{{ python_version }}"]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 80
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__.:",
]

[tool.hatch.envs.test]
installer = "uv"
dependencies = [
    "pytest",
    "pytest-cov",
]

[[tool.hatch.envs.test.matrix]]
python = ["3.12", "3.13", "3.14"]

[tool.hatch.envs.test.scripts]
run = "pytest"
cov = "pytest --cov={{ python_version }} --cov-report=term-missing"
